### ISSUE TITLE
Need to lock certain pages behind log-in

### ISSUE THREAD

**Issue by Ajolo** [peachfuzz/spu2you#7]
Users should not be able to visit every page without first visiting splash page and logging in, unless they are already deemed logged in by the browser's cookies. May be able to solve this using AWS login handling, otherwise see:
https://stackoverflow.com/questions/42322399/react-router-how-to-indexredirect-to-dynamic-route
... for an example of how we might use our router to 'lock' pages behind login.

**Comment by peachfuzz** [comment]
Donezo via Azure 😃
